name: Linux CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Linux compilation
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build
        run: ./scripts/build.sh
