name: Windows CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    name: Windows compilation
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build
        run: ./scripts/build.bat
